version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: financialdb
      POSTGRES_USER: financialuser
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: ./backend
    command: gunicorn financial_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  data_collector:
    build: ./backend
    command: python main/data_collector.py
    depends_on:
      - rabbitmq

  event_notification:
    build: ./backend
    command: python main/event_notification.py
    depends_on:
      - rabbitmq
